-- Add profile fields to users table
-- Run this SQL to add first_name, last_name, and country fields

ALTER TABLE users 
ADD COLUMN first_name VARCHAR(50) NULL AFTER email,
ADD COLUMN last_name VARCHAR(50) NULL AFTER first_name,
ADD COLUMN country VARCHAR(3) NULL AFTER last_name;

-- Add indexes for better performance
CREATE INDEX idx_users_name ON users(first_name, last_name);
CREATE INDEX idx_users_country ON users(country);

-- Insert default email templates
INSERT INTO email_templates (template_key, subject, body, is_active) VALUES 
('welcome', 'Welcome to {{site_name}} - Start Earning Today!', '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Welcome to {{site_name}}</title><style>body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }.header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }.content { background: white; padding: 30px; border: 1px solid #ddd; border-top: none; border-radius: 0 0 10px 10px; }.welcome-box { background: #e8f5e8; padding: 20px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #28a745; }.btn { display: inline-block; padding: 12px 24px; background: #667eea; color: white; text-decoration: none; border-radius: 5px; margin: 10px 5px; }.footer { font-size: 12px; color: #666; text-align: center; margin-top: 30px; border-top: 1px solid #eee; padding-top: 20px; }</style></head><body><div class="header"><div style="font-size: 3rem; margin-bottom: 15px;">🌟</div><h1 style="margin: 0;">Welcome to {{site_name}}!</h1><p style="margin: 10px 0 0; opacity: 0.9;">Your journey to financial freedom starts here</p></div><div class="content"><h2 style="color: #28a745;">🎉 Account Created Successfully!</h2><p>Hello {{first_name}} {{last_name}},</p><div class="welcome-box"><p><strong>Congratulations!</strong> Your {{site_name}} account has been created successfully. You can now start earning daily profits through our premium router rental platform.</p></div><h3>🚀 Next Steps:</h3><ol><li>Make your first deposit (minimum $100)</li><li>Choose an investment plan that suits you</li><li>Start earning daily profits up to 2%</li><li>Share your referral code and earn 10% commission</li></ol><div style="text-align: center; margin: 30px 0;"><a href="{{site_url}}/user/dashboard.php" class="btn">🎛️ Access Dashboard</a><a href="{{site_url}}/user/deposit.php" class="btn">💰 Make Deposit</a></div><p style="margin-top: 30px;">Best regards,<br><strong>Star Rent Team</strong><br><a href="{{site_url}}">{{site_name}}</a></p><div class="footer"><p>For support, contact us at <a href="mailto:{{support_email}}">{{support_email}}</a></p><p><a href="{{site_url}}">Visit our website</a></p></div></div></body></html>', 1),

('deposit_confirmed', '✅ Deposit Confirmed - {{site_name}}', '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Deposit Confirmed</title><style>body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }.header { background: linear-gradient(135deg, #28a745, #20c997); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }.content { background: white; padding: 30px; border: 1px solid #ddd; border-top: none; border-radius: 0 0 10px 10px; }.success-box { background: #d4edda; padding: 20px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #28a745; }.btn { display: inline-block; padding: 12px 24px; background: #28a745; color: white; text-decoration: none; border-radius: 5px; margin: 10px 0; }.footer { font-size: 12px; color: #666; text-align: center; margin-top: 30px; border-top: 1px solid #eee; padding-top: 20px; }</style></head><body><div class="header"><h1 style="margin: 0;">✅ Deposit Confirmed!</h1><p style="margin: 10px 0 0; opacity: 0.9;">Your funds have been added to your account</p></div><div class="content"><p>Hello {{first_name}} {{last_name}},</p><div class="success-box"><p><strong>Great news!</strong> Your deposit of <strong>${{amount}}</strong> has been confirmed and added to your {{site_name}} account.</p></div><h3>📊 Transaction Details:</h3><ul><li><strong>Amount:</strong> ${{amount}}</li><li><strong>Currency:</strong> {{currency}}</li><li><strong>Transaction ID:</strong> {{transaction_id}}</li><li><strong>Date:</strong> {{date}}</li></ul><p>You can now start investing and earning daily profits!</p><div style="text-align: center; margin: 30px 0;"><a href="{{site_url}}/user/dashboard.php" class="btn">📊 View Dashboard</a><a href="{{site_url}}/user/investments.php" class="btn">💰 Start Investing</a></div><p style="margin-top: 30px;">Best regards,<br><strong>Star Rent Team</strong><br><a href="{{site_url}}">{{site_name}}</a></p><div class="footer"><p>For support, contact us at <a href="mailto:{{support_email}}">{{support_email}}</a></p></div></div></body></html>', 1)

ON DUPLICATE KEY UPDATE 
subject = VALUES(subject),
body = VALUES(body),
is_active = VALUES(is_active);